In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

# Concatenate 连接

## 在 array 中

- <font color="blue">参数 axis ：默认值为 0，增加行数；值为1，增加列。</font>

In [3]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
arr2 = np.arange(9).reshape(3,3)
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.concatenate([arr1,arr2]) # axis - 值默认为 0,增加行数

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
np.concatenate([arr1,arr2],axis=1) # axis - 值为1，增加列

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

## 在 Series 中

- <font color="blue">参数 axis ：默认值为 0，增加行数，结果仍为 Series；值为1，增加行数，结果为 DataFrame,且将没有的原值填充为 NaN。</font>

In [8]:
s1 = Series([1,2,3],index=['X','Y','Z'])
s1

X    1
Y    2
Z    3
dtype: int64

In [10]:
s2 = Series([4,5],index=['A','B'])
s2

A    4
B    5
dtype: int64

In [11]:
pd.concat([s1,s2]) # axis = 0，结果仍为 Series

X    1
Y    2
Z    3
A    4
B    5
dtype: int64

In [12]:
pd.concat([s1,s2],axis=1) # axis = 1，结果为 DataFrame, 且没有的原值，用 NaN 填充

0    1
X  1.0  NaN
Y  2.0  NaN
Z  3.0  NaN
A  NaN  4.0
B  NaN  5.0

## 在 DataFrame 中

- <font color="blue">参数 axis ：默认值为 0，连接两个 DataFrame</font>

In [19]:
df1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])
df1

X         Y         Z
0  0.925016  0.736804  2.446533
1  2.055644  0.336721 -0.566095
2 -0.504170 -0.017930  1.193248
3  1.632534 -0.086261  0.182530

In [22]:
df2 = DataFrame(np.random.randn(3,3),columns=['X','Y','A'])
df2

X         Y         A
0 -0.927622 -1.345777  0.582421
1  0.508005  0.963766 -0.879130
2  0.158988 -1.155001  0.181003

In [23]:
pd.concat([df1,df2])

X         Y         Z         A
0  0.925016  0.736804  2.446533       NaN
1  2.055644  0.336721 -0.566095       NaN
2 -0.504170 -0.017930  1.193248       NaN
3  1.632534 -0.086261  0.182530       NaN
0 -0.927622 -1.345777       NaN  0.582421
1  0.508005  0.963766       NaN -0.879130
2  0.158988 -1.155001       NaN  0.181003

# Combine 联合，填充

两个 数据类型 ：s1、s2

- <font color="blue"> s1.combine_first(s2) ：用 s2 的数据填充 s1 中值为 NaN的数据, 不改变 s1 原有的值。</font>


## 在 Series 中



In [25]:
s1 = Series([2,np.nan,4,np.nan],index=['A','B','C','D'])
s1

A    2.0
B    NaN
C    4.0
D    NaN
dtype: float64

In [26]:
s2 = Series([1,2,3,4],index=['A','B','C','D'])
s2

A    1
B    2
C    3
D    4
dtype: int64

In [31]:
s1.combine_first(s2) # 用 s2 的数据填充 s1 中值为 NaN的数据, 不改变 s1 原有的值

A    2.0
B    2.0
C    4.0
D    4.0
dtype: float64

## 在 DataFrame 中


In [34]:
df1 = DataFrame({
    'X':[1,np.nan,3,np.nan],
    'Y':[5,np.nan,7,np.nan],
    'Z':[9,np.nan,11,np.nan]

})
df1

X    Y     Z
0  1.0  5.0   9.0
1  NaN  NaN   NaN
2  3.0  7.0  11.0
3  NaN  NaN   NaN

In [39]:
df2 = DataFrame({
    'Z':[np.nan,10,np.nan,12],
    'A':[1,2,3,4]

})
df2

Z  A
0   NaN  1
1  10.0  2
2   NaN  3
3  12.0  4

In [38]:
df1.combine_first(df2)

A    X    Y     Z
0  1.0  1.0  5.0   9.0
1  2.0  NaN  NaN  10.0
2  3.0  3.0  7.0  11.0
3  4.0  NaN  NaN  12.0