# Pandas Series

Series是一种类似于一维数组的对象，它由一组数据（各种NumPy数据类型）以及一组与之相关的数据标签（即索引）组成。

In [3]:
import numpy as np
import pandas as pd

## 创建 Series

### <font color="blue">方式1：Series属性+数组: pd.Series(array_list)</font>

In [4]:
s1 =  pd.Series([1,2,3,4])   # Way 1 
s1                 # 列出 所有 index 与其 对应的值

0    1
1    2
2    3
3    4
dtype: int64

In [5]:
s1.values   # values attribute - 查看 Series 的 值

array([1, 2, 3, 4])

In [6]:
s1.index   #  index attribute - 查看 Series 的 index value for start, stop, and step.

RangeIndex(start=0, stop=4, step=1)

### <font color="blue">方式2：Series 属性 + np.arange 产生数组 : pd.Series(np.arange())</font>

In [8]:
s2 = pd.Series(np.arange(10)) # Way 2
s2

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

### <font color="blue">方式3： Series + array_dictionary 为插入的array值 设置 index: pd.Series(array_dictionary)</font>

In [10]:
s3 = pd.Series({'1' : 1, '2' : 2, '3' : 3}) # Way 3
s3

1    1
2    2
3    3
dtype: int64

In [11]:
s3.values

array([1, 2, 3])

In [12]:
s3.index

Index(['1', '2', '3'], dtype='object')

### <font color="blue">方式4：Series + array + index 为插入的array值 设置 index : pd.Series(array_lsit, index_list)</font>

In [14]:
s4 = pd.Series([1,2,3,4], index=['A','B','C','D']) # Way 4
s4

A    1
B    2
C    3
D    4
dtype: int64

In [16]:
s4.values

array([1, 2, 3, 4])

In [17]:
s4.index

Index(['A', 'B', 'C', 'D'], dtype='object')

In [18]:
s4['A']   # 取 index = 'A' 的 value

1

In [19]:
s4[s4>2]  # 取所有 values > 2 的 values

C    3
D    4
dtype: int64

#### - <font color="orange">to_dict()</font> method - 将 array 转换成 dictionary

In [26]:
s4.to_dict()  # 将 to_dict() method - 将 array 转换成 dictionary

{'A': 1, 'B': 2, 'C': 3, 'D': 4}

In [25]:
s4

A    1
B    2
C    3
D    4
dtype: int64

In [29]:
s5 = pd.Series(s4.to_dict())
s5

A    1
B    2
C    3
D    4
dtype: int64

In [31]:
index_1 = ['A','B','C','D','E']
s6 = pd.Series(s5, index = index_1)
s6

A    1.0
B    2.0
C    3.0
D    4.0
E    NaN
dtype: float64

#### - <font color="orange"> name </font> attribute : 赋名 属性</font>

In [33]:
s6.name = 'demo' # Series.name attribute - 给 Series 赋名
s6

A    1.0
B    2.0
C    3.0
D    4.0
E    NaN
Name: demo, dtype: float64

In [35]:
s6.index.name = "demo index" # Series.index.name - 给 Series index 赋名
s6

demo index
A    1.0
B    2.0
C    3.0
D    4.0
E    NaN
Name: demo, dtype: float64

In [36]:
s6.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object', name='demo index')

#### <font color="orange">replace</font> : 代替 series 中的值

代替一个值：

- Way1：传入参数
  replace(to_replace_value,target_value)
- Way2：传入字典
  replace({to_replace_value：target_value}）

代替多个值：

- replace([to_replace_valus list],[target_values list])


In [37]:
s = pd.Series(np.arange(10)) # 创建一个 0 - 9 的数列
s

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

### 替代单个值

#### Way 1 ：传入参数

In [50]:
s # 原来数据

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [40]:
s.replace(1,np.nan) # 将数列中的 value 为 1 的值，用 NaN 代替

0    0.0
1    NaN
2    2.0
3    3.0
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

#### Way 2：传入字典

In [48]:
s # 原来数据

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [49]:
s.replace({2:np.nan}) # 以字典形式代替：将值为 2 的元素用 NaN 代替

0    0.0
1    1.0
2    NaN
3    3.0
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

### 替代多个值


In [47]:
s # 原来数据

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [46]:
s.replace([1,2,3],[11,12,13]) # 将值为1,2,3元素 替换为 11,12,13

0     0
1    11
2    12
3    13
4     4
5     5
6     6
7     7
8     8
9     9
dtype: int64