# Python 中创建数组以及访问

## Method in np Modules
 


In [1]:
import numpy as np

In [3]:
# create list_1
list_1 = [1,2,3,4]
list_1

[1, 2, 3, 4]

## <font color="orange"> np.array()</font>

change lists to multi-dimensional array, and each list is a signle dimensional

In [4]:
# use array method from np
# to change a list to a 1x4 array
array_1 = np.array(list_1)
array_1

array([1, 2, 3, 4])

In [5]:
# create list_2
list_2 = [5,6,7,8]
list_2 

[5, 6, 7, 8]

In [7]:
# use array method from np
# to change two lists to a 2x4 array
array_2 = np.array([list_1,list_2])
array_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
# print the shape of array_2
array_2.shape

(2, 4)

In [9]:
# print the size of array_2
array_2.size

8

In [10]:
# print the type of array_2
# array_2 all elements are int so it also is int type
array_2.dtype

dtype('int64')

In [12]:
# create a new array
array_3 = np.array([[1.0,2,3],[4.0,5,6]])
array_3

array([[1., 2., 3.],
       [4., 5., 6.]])

In [13]:
# print the type of array_3
# array_3 some of elements are float so it also is float type
array_3.dtype

dtype('float64')

## <font color="orange"> np.arange(start,end,length) </font>

randomly create a array,its values begin from start, end at end - 1, and the interval is length.

In [15]:
# create a new array_4 from 1 to 9 and interval is 2
array_4 = np.arange(1,10,2)
array_4

array([1, 3, 5, 7, 9])

## <font color="orange"> np.zeros() </font>
create a matrix with 0
 - single - parameter : the quality of 1-D matrix
 - multi - parameter [n,m]: the shape of n x m matrix

In [16]:
# create a 1 x 5 matrix with 0 values
np.zeros(5) 

array([0., 0., 0., 0., 0.])

In [17]:
# create a 2 x 3 matrix with 0 values
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

## <font color="orange">np.eye()</font>

Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [33]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
np.eye(5).dtype

dtype('float64')

In [19]:
# Return a 2-D array with ones on the diagonal and zeros elsewhere.
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.eye(5).dtype

dtype('float64')

## Array 操作

- 与 Python list 切片操作一样

# 1-D Array

In [22]:
# Create a array from 1 to 9
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# return the element of 1 index
a[1]

2

In [24]:
# return the elements from 1 to 5
a[1:5]

array([2, 3, 4, 5])

### 2-D Array


In [26]:
# 2—D Array
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
# return 2 row, 0 column element
b[1][0]

4

In [28]:
# or
b[1,0]

4

# 3-D Array

In [30]:
# 3-D Array
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
# return elements in 0 - 1 rows, 1 - 2 columns
c[:2,1:]

array([[2, 3],
       [5, 6]])