# Matrix Creation

In [3]:
import numpy

numpy.random.rand(shape) - create randomly initialized matrix

In [4]:
w_1 = numpy.random.rand(3,3)
print('Shape: ', w_1.shape)
print(w_1)

Shape:  (3, 3)
[[0.20211926 0.61549642 0.65318188]
 [0.50430628 0.86353795 0.71579787]
 [0.79694803 0.19440819 0.31980278]]


In [5]:
w_2 = numpy.random.rand(3,1)
print('Shape: ', w_2.shape)
print(w_2)

Shape:  (3, 1)
[[0.03954771]
 [0.09904562]
 [0.35312335]]


# Matrix Transpose

numpy.asarray - convert list to numpy array / matrix

In [6]:
w_1 = numpy.asarray([[1],[2],[3]])
print('Shape: ', w_1.shape)
print(w_1)

Shape:  (3, 1)
[[1]
 [2]
 [3]]


.T attribute - computes the transpose of matrix

In [7]:
w_1 = w_1.T
print('Shape: ', w_1.shape)
print(w_1)

Shape:  (1, 3)
[[1 2 3]]


# Matrix Multiplication

numpy.dot(w1,w2) - compute dot product / matrix multiplication for matrixes w1 and w2

In [8]:
w_1 = numpy.asarray([[1,2,3]])
print('Shape: ', w_1.shape)
print(w_1)

print('--------')

w_2 = numpy.asarray([[1,1,1],[0,1,1],[0,0,1]])
print('Shape: ', w_2.shape)
print(w_2)

Shape:  (1, 3)
[[1 2 3]]
--------
Shape:  (3, 3)
[[1 1 1]
 [0 1 1]
 [0 0 1]]


In [9]:
w_3 = numpy.dot(w_1, w_2)
print('Shape: ', w_3.shape)
print(w_3)

Shape:  (1, 3)
[[1 3 6]]


In [10]:
numpy.dot(w_2,w_1)

ValueError: shapes (3,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

Simple multiplication sign(*) will make element-wise multiplication

In [11]:
w_4 = w_3 * 2
print('Shape: ', w_4.shape)
print(w_4)

Shape:  (1, 3)
[[ 2  6 12]]


# Forward Propagation

In [12]:
import numpy
I = numpy.asarray([[0.9,0.1,0.8]]).T
print('Shape: ', I.shape)
print(I)

Shape:  (3, 1)
[[0.9]
 [0.1]
 [0.8]]


In [13]:
W_input_hidden = numpy.asarray(
                    [[0.9, 0.3, 0.4],
                     [0.2, 0.8, 0.2],
                     [0.1, 0.5, 0.6]])
print('Shape: ', W_input_hidden.shape)
print(W_input_hidden)

print('\n----------\n')

W_hidden_output = numpy.asarray(
                [[0.3, 0.7, 0.5], 
                 [0.6, 0.5, 0.2], 
                 [0.8, 0.1, 0.9]])
print('Shape: ', W_input_hidden.shape)
print(W_input_hidden)

Shape:  (3, 3)
[[0.9 0.3 0.4]
 [0.2 0.8 0.2]
 [0.1 0.5 0.6]]

----------

Shape:  (3, 3)
[[0.9 0.3 0.4]
 [0.2 0.8 0.2]
 [0.1 0.5 0.6]]


In [14]:
X_hidden = numpy.dot(W_input_hidden, I)
print(X_hidden.shape)
print(X_hidden)

(3, 1)
[[1.16]
 [0.42]
 [0.62]]


# API scipy.special - call the sigmoid function

In [15]:
import scipy.special
sigmoid_function = lambda x : scipy.special.expit(x)

In [16]:
O_hidden = sigmoid_function(X_hidden)
print(O_hidden.shape)
print(O_hidden)

(3, 1)
[[0.76133271]
 [0.60348325]
 [0.65021855]]


In [17]:
X_output = numpy.dot(W_hidden_output,O_hidden)
print(X_output.shape)
print(X_output)

(3, 1)
[[0.97594736]
 [0.88858496]
 [1.25461119]]


In [18]:
O_output = sigmoid_function(X_output)
print(O_output.shape)
print(O_output)

(3, 1)
[[0.72630335]
 [0.70859807]
 [0.77809706]]


# Backward Propagation

## Old Weights

In [19]:
print(W_input_hidden.shape)
print(W_input_hidden)
print('-------')
print(W_hidden_output.shape)
print(W_hidden_output)

(3, 3)
[[0.9 0.3 0.4]
 [0.2 0.8 0.2]
 [0.1 0.5 0.6]]
-------
(3, 3)
[[0.3 0.7 0.5]
 [0.6 0.5 0.2]
 [0.8 0.1 0.9]]


In [20]:
target = numpy.asarray([[0.6,0.8,0.5]]).T
print('--Sample Target--')
print(target.shape)
print(target)

--Sample Target--
(3, 1)
[[0.6]
 [0.8]
 [0.5]]


In [24]:
output_error = target - O_output
print(output_error)

hidden_error = numpy.dot(W_hidden_output.T, output_error)
print(hidden_error)

W_hidden_output += 0.01 * numpy.dot(output_error * O_output * (1 - O_output), O_hidden.T)
print(W_hidden_output)

W_input_hidden += 0.01 * numpy.dot(hidden_error * O_hidden * (1 - O_hidden), I.T)
print(W_input_hidden)

[[-0.12630335]
 [ 0.09140193]
 [-0.27809706]]
[[-0.20511068]
 [-0.07019068]
 [-0.29480265]]
[[0.2992354  0.69939392 0.49934699]
 [0.60057475 0.50045559 0.20049087]
 [0.79853773 0.09884091 0.89875114]]
[[0.89865693 0.29985077 0.39880616]
 [0.19939392 0.79993266 0.19946126]
 [0.09758481 0.49973165 0.59785316]]


In [33]:
print(W_input_hidden.shape)
print(W_input_hidden)

print('\n---------\n')
print(W_hidden_output.shape)
print(W_hidden_output)


(3, 3)
[[0.89932801 0.29992533 0.39940268]
 [0.19969649 0.79996628 0.19973021]
 [0.09879192 0.49986577 0.59892615]]

---------

(3, 3)
[[0.2996177  0.69969696 0.49967349]
 [0.60028738 0.50022779 0.20024544]
 [0.79926886 0.09942045 0.89937557]]


# Sample Training and Testing

In [34]:
n_of_epochs = 800

I = numpy.asarray([[0.9, 0.1, 0.8]]).T
target = numpy.asarray([[0.6, 0.8, 0.5]]).T

W_input_hidden = numpy.asarray(
                    [[0.9, 0.3, 0.4],
                     [0.2, 0.8, 0.2],
                     [0.1, 0.5, 0.6]])

W_hidden_output = numpy.asarray(
                    [[0.3, 0.7, 0.5],
                     [0.6, 0.5, 0.2],
                     [0.8, 0.1, 0.9]])

In [37]:
print('Weight Matrixes')
print(W_input_hidden.shape)
print(W_input_hidden)
print('-------')
print(W_hidden_output.shape)
print(W_hidden_output)

print('\nTarget:\n', target, '\n')


# Forward Pass
X_hidden = numpy.dot(W_input_hidden, I)
O_hidden = sigmoid_function(X_hidden)
X_output = numpy.dot(W_hidden_output, O_hidden)
O_output = sigmoid_function(X_output)
print('Output Before Training:\n', O_output)

# Training
print('\n---Training Started---')

for epoch in range(n_of_epochs):

  # Forward Pass
  X_hidden = numpy.dot(W_input_hidden, I)
  O_hidden = sigmoid_function(X_hidden)
  X_output = numpy.dot(W_hidden_output, O_hidden)
  O_output = sigmoid_function(X_output)

  # Backward Pass
  output_error = target - O_output
  hidden_error = numpy.dot(W_hidden_output.T, output_error)
  W_hidden_output += 0.1 * numpy.dot(output_error * O_output * (1 - O_output), O_hidden.T)
  W_input_hidden += 0.1 * numpy.dot(hidden_error * O_hidden * (1 - O_hidden), I.T)

  if epoch % 100 == 0:
    print('Epoch:', epoch)
    total_error = numpy.sum(output_error ** 2)
    print('Error:', '{0:.10f}'.format(total_error))

print('---Training Fininshed---\n')


# Forward Pass
X_hidden = numpy.dot(W_input_hidden, I)
O_hidden = sigmoid_function(X_hidden)
X_output = numpy.dot(W_hidden_output, O_hidden)
O_output = sigmoid_function(X_output)
print('Output After Training:\n', O_output)

print('\nWeight Matrixes')
print(W_input_hidden.shape)
print(W_input_hidden)
print('-------')
print(W_hidden_output.shape)
print(W_hidden_output)

Weight Matrixes
(3, 3)
[[0.9 0.3 0.4]
 [0.2 0.8 0.2]
 [0.1 0.5 0.6]]
-------
(3, 3)
[[0.3 0.7 0.5]
 [0.6 0.5 0.2]
 [0.8 0.1 0.9]]

Target:
 [[0.6]
 [0.8]
 [0.5]] 

Output Before Training:
 [[0.72630335]
 [0.70859807]
 [0.77809706]]

---Training Started---
Epoch: 0
Error: 0.1016448219
Epoch: 100
Error: 0.0287427015
Epoch: 200
Error: 0.0081838235
Epoch: 300
Error: 0.0023825505
Epoch: 400
Error: 0.0007263831
Epoch: 500
Error: 0.0002367784
Epoch: 600
Error: 0.0000825510
Epoch: 700
Error: 0.0000303607
---Training Fininshed---

Output After Training:
 [[0.60127786]
 [0.79691272]
 [0.5006452 ]]

Weight Matrixes
(3, 3)
[[ 0.81474342  0.29052705  0.32421638]
 [ 0.40407065  0.82267452  0.38139613]
 [-0.49263378  0.4341518   0.07321442]]
-------
(3, 3)
[[-0.00712505  0.43671401  0.28720227]
 [ 0.91358922  0.77108557  0.4126951 ]
 [ 0.16012332 -0.44541396  0.45119395]]


In [38]:
import numpy
import scipy.special

# neural network class definition
class neuralNetwork:
    
    
    # initialise the neural network
    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
        
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes
        
        print('Input Nodes: ', self.inodes, 'Hidden Nodes: ', self.hnodes, 'Output Nodes: ', self.onodes)
        self.wih = (numpy.random.rand(self.hnodes, self.inodes) - 0.5)
        self.who = (numpy.random.rand(self.onodes, self.hnodes) - 0.5)

        
        print('Matrix 1: ', '\n', self.wih)
        print('Matrix 2: ', '\n', self.who)
        
        self.lr = learningrate
        
        # activation function is the sigmoid function
        self.activation_function = lambda x: scipy.special.expit(x)        
                
       
        pass

    
    # train the neural network
    def train(self, inputs_list, targets_list):
       # convert inputs list to 2d array
        inputs = numpy.array(inputs_list, ndmin=2).T
        targets = numpy.array(targets_list, ndmin=2).T
        
        # calculate signals into hidden layer
        hidden_inputs = numpy.dot(self.wih, inputs)
        # calculate the signals emerging from hidden layer
        hidden_outputs = self.activation_function(hidden_inputs)
        
        # calculate signals into final output layer
        final_inputs = numpy.dot(self.who, hidden_outputs)
        # calculate the signals emerging from final output layer
        final_outputs = self.activation_function(final_inputs)
        
        # output layer error is the (target - actual)
        output_errors = targets - final_outputs
        # hidden layer error is the output_errors, split by weights, recombined at hidden nodes
        hidden_errors = numpy.dot(self.who.T, output_errors) 
        
        # update the weights for the links between the hidden and output layers
        self.who += self.lr * numpy.dot((output_errors * final_outputs * (1.0 - final_outputs)), numpy.transpose(hidden_outputs))
        
        # update the weights for the links between the input and hidden layers
        self.wih += self.lr * numpy.dot((hidden_errors * hidden_outputs * (1.0 - hidden_outputs)), numpy.transpose(inputs))
        
       
        pass

    
    # query the neural network
    def query(self, inputs_list):
        # convert inputs list to 2d array
        inputs = numpy.array(inputs_list, ndmin=2).T
        
        # calculate signals into hidden layer
        hidden_inputs = numpy.dot(self.wih, inputs)
        # calculate the signals emerging from hidden layer
        hidden_outputs = self.activation_function(hidden_inputs)
        
        # calculate signals into final output layer
        final_inputs = numpy.dot(self.who, hidden_outputs)
        # calculate the signals emerging from final output layer
        final_outputs = self.activation_function(final_inputs)
        
        return final_outputs
    
# number of input, hidden and output nodes
input_nodes = 3
hidden_nodes = 2
output_nodes = 2

# learning rate
learning_rate = 0.1

# create instance of neural network
n = neuralNetwork(input_nodes,hidden_nodes,output_nodes, learning_rate)

Input Nodes:  3 Hidden Nodes:  2 Output Nodes:  2
Matrix 1:  
 [[-0.04740226  0.21093415 -0.46485602]
 [ 0.28655473  0.27772149  0.25144789]]
Matrix 2:  
 [[ 0.232186   -0.25050484]
 [-0.30187062 -0.08580363]]
