# Part 1

### <font color="blue"> In Step Format </font>

In [1]:
import numpy              # import numpy API

### Forward Pass

In [2]:
# Generate input values for input layer1
input_values = numpy.asarray([[0.9, 0.1, 0.8]]).T
print("Input values for input layer 1 : ", input_values)

Input values for input layer 1 :  [[0.9]
 [0.1]
 [0.8]]


In [3]:
# Generate the weights from input layer1 to hidden layer2
weights_input_hidden = numpy.asarray([[0.9,0.3,0.4],
                                     [0.2,0.8,0.2],
                                     [0.1,0.5,0.6]])
print("Weights for input layer 1 to hidden layer 2 : ", weights_input_hidden)


Wights for input layer 1 to hidden layer 2 :  [[0.9 0.3 0.4]
 [0.2 0.8 0.2]
 [0.1 0.5 0.6]]


In [6]:
# Generate the input values for hidden layer2 before sigmoid function
input_before_hidden_values = numpy.dot(weights_input_hidden,input_values)
print("Input values for hidden layer2 before sigmoid function: ", input_before_hidden_values)


Input values for hidden layer2 before sigmoid function:  [[1.16]
 [0.42]
 [0.62]]


In [8]:
import scipy.special      # import scipy.special API to use the sigmoid function
sigmoid_function = lambda x : scipy.special.expit(x) # define the sigmoid function

In [9]:
# Generate the input values for output layer 3 after sigmoid function
input_after_output_values = sigmoid_function(input_before_hidden_values)
print("Input values for output layer 3 : ", input_after_output_values)

Input values for output layer 3 :  [[0.76133271]
 [0.60348325]
 [0.65021855]]


In [11]:
# Generate the weights from hidden layer2 to output layer3
weights_hidden_output = numpy.asarray([[0.3, 0.7, 0.5],
                                     [0.6, 0.5, 0.2],
                                     [0.8, 0.1, 0.9]])
print("Weights for hidden layer 2 to output layer 3 : ", weights_hidden_output)

Wights for hidden layer 2 to output layer 3 :  [[0.3 0.7 0.5]
 [0.6 0.5 0.2]
 [0.8 0.1 0.9]]


In [12]:
# Generate the input values for output layer3 before sigmoid function
input_before_output_values = numpy.dot(weights_hidden_output,input_after_output_values)
print("Input values for output layer3 before sigmoid function : ",input_before_output_values)


Input values for output layer3 before sigmoid function :  [[0.97594736]
 [0.88858496]
 [1.25461119]]


### Output Values

In [17]:
# Generate the output values  after sigmoid function
output = sigmoid_function(input_before_output_values)
print("Output values for output layer3 after sigmoid function : ",output)


Input values for output layer3 after sigmoid function :  [[0.72630335]
 [0.70859807]
 [0.77809706]]


### Backward Pass

#### Old Weights

In [32]:
# the weights from input layer1 to hidden layer2
print("Old weights for input layer 1 to hidden layer 2 : ", weights_input_hidden)

print("\n------\n")

# the weights from hidden layer2 to output layer3
print("Old weights for hidden layer 2 to output layer 3 : ", weights_hidden_output)

Old weights for input layer 1 to hidden layer 2 :  [[0.9 0.3 0.4]
 [0.2 0.8 0.2]
 [0.1 0.5 0.6]]

------

Old weights for hidden layer 2 to output layer 3 :  [[0.3 0.7 0.5]
 [0.6 0.5 0.2]
 [0.8 0.1 0.9]]


In [33]:
# Generate the target values
target = numpy.asarray([[0.6,0.8,0.5]]).T
print("Target values : ", target)

Target values :  [[0.6]
 [0.8]
 [0.5]]


In [34]:
# Generate the output error which equals to target values minus  output values
output_error = target - output
print("Output errors : ", output_error)

Output errors :  [[-0.12630335]
 [ 0.09140193]
 [-0.27809706]]


In [35]:
# Generate the hidden error
hidden_error = numpy.dot(weights_hidden_output.T, output_error)
print("Hidden error : ", hidden_error)

Hidden error :  [[-0.20552749]
 [-0.07052108]
 [-0.29515864]]


#### New Weights

In [45]:
# weights of output layer3 to hidden layer2
weights_hidden_output += 0.01 * numpy.dot(output_error * output * (1 - output), input_after_output_values.T)
print("Get weights of output layer3 to hidden layer2 :", weights_hidden_output)

Get weights of output layer3 to hidden layer2 : [[0.29942655 0.69954544 0.49951024]
 [0.60043107 0.50034169 0.20036815]
 [0.7989033  0.09913068 0.89906336]]


In [44]:
# weights of hidden layer2 to input layer1
weights_input_hidden += 0.01 * numpy.dot(hidden_error *input_after_output_values * (1 - input_after_output_values), input_values.T)
print("Get weights of hidden layer2 to input layer1 :", weights_input_hidden)

Get weights of hidden layer2 to input layer1 : [[0.89932778 0.29992531 0.39940247]
 [0.19969625 0.79996625 0.19973   ]
 [0.09879167 0.49986574 0.59892593]]


## <font color="blue"> In Class Format </font>

In [69]:
import numpy              # import numpy API
import scipy.special      # import scipy.special API to use the sigmoid function

class neuralNetworkFirstStudy:
    
    # constructor function to initialization the nural network
    def __init__(self, input_values, weights_input_hidden,weights_hidden_output,target):
        self.input_values = numpy.asarray(input_values).T
        self.weights_input_hidden = numpy.asarray(weights_input_hidden)
        self.weights_hidden_output = numpy.asarray(weights_hidden_output)
        self.target = numpy.asarray(target).T
        
        print("\n****** Forward Pass ******\n")
        
        print("Input values for input layer 1 : ", self.input_values)

        print("\n------\n")
        
        print("Weights for input layer 1 to hidden layer 2 : ", self.weights_input_hidden)

        print("\n------\n")
        
        print("Weights for hidden layer 2 to output layer 3 : ", self.weights_hidden_output)
        
        print("\n------\n")
        
        print("Target values : ", self.target)

        print("\n------\n")
        
        # Generate the input values for hidden layer2 before sigmoid function
        self.input_before_hidden_values = numpy.dot(self.weights_input_hidden,self.input_values)
        
        print("Input values for hidden layer2 before sigmoid function: ", self.input_before_hidden_values)

        print("\n------\n")


        sigmoid_function = lambda x : scipy.special.expit(x) # define the sigmoid function

        # Generate the input values for output layer 3 after sigmoid function
        self.input_after_output_values = sigmoid_function(self.input_before_hidden_values)
        print("Input values for output layer 3 : ", self.input_after_output_values)

        print("\n------\n")
        
        # Generate the input values for output layer3 before sigmoid function
        self.input_before_output_values = numpy.dot(self.weights_hidden_output,self.input_after_output_values)
        print("Input values for output layer3 before sigmoid function : ",self.input_before_output_values)

        print("\n------\n")

        # Generate the output values  after sigmoid function
        self.output = sigmoid_function(self.input_before_output_values)
        print("Output values for output layer3 after sigmoid function : ",self.output)

        print("\n------\n")
        
        print("\n****** Backward Pass ******\n")

        # Generate the output error which equals to target values minus  output values
        self.output_error = self.target - self.output
        print("Output errors : ", self.output_error)

        print("\n------\n")

        # Generate the hidden error
        self.hidden_error = numpy.dot(self.weights_hidden_output.T, self.output_error)
        print("Hidden error : ", self.hidden_error)

        print("\n------\n")
        
        # weights of output layer3 to hidden layer2
        self.weights_hidden_output += 0.01 * numpy.dot(self.output_error * self.output * (1 - self.output), self.input_after_output_values.T)
        print("Get weights of output layer3 to hidden layer2 :", self.weights_hidden_output)

        print("\n------\n")

        # weights of hidden layer2 to input layer1
        self.weights_input_hidden += 0.01 * numpy.dot(self.hidden_error *self.input_after_output_values * (1 - self.input_after_output_values), self.input_values.T)
        print("Get weights of hidden layer2 to input layer1 :", self.weights_input_hidden)

        pass

# Generate input values for input layer1
input_values = [[0.9, 0.1, 0.8]]

# Generate the weights from input layer1 to hidden layer2
weights_input_hidden = [[0.9,0.3,0.4],[0.2,0.8,0.2],[0.1,0.5,0.6]]

# Generate the weights from hidden layer2 to output layer3
weights_hidden_output = [[0.3, 0.7, 0.5],[0.6, 0.5, 0.2],[0.8, 0.1, 0.9]]

# Generate the target values
target = [[0.6,0.8,0.5]]

# Create an instance of neural network
n = neuralNetworkFirstStudy(input_values,weights_input_hidden,weights_hidden_output,target)


****** Forward Pass ******

Input values for input layer 1 :  [[0.9]
 [0.1]
 [0.8]]

------

Weights for input layer 1 to hidden layer 2 :  [[0.9 0.3 0.4]
 [0.2 0.8 0.2]
 [0.1 0.5 0.6]]

------

Weights for hidden layer 2 to output layer 3 :  [[0.3 0.7 0.5]
 [0.6 0.5 0.2]
 [0.8 0.1 0.9]]

------

Target values :  [[0.6]
 [0.8]
 [0.5]]

------

Input values for hidden layer2 before sigmoid function:  [[1.16]
 [0.42]
 [0.62]]

------

Input values for output layer 3 :  [[0.76133271]
 [0.60348325]
 [0.65021855]]

------

Input values for output layer3 before sigmoid function :  [[0.97594736]
 [0.88858496]
 [1.25461119]]

------

Output values for output layer3 after sigmoid function :  [[0.72630335]
 [0.70859807]
 [0.77809706]]

------


****** Backward Pass ******

Output errors :  [[-0.12630335]
 [ 0.09140193]
 [-0.27809706]]

------

Hidden error :  [[-0.20552749]
 [-0.07052108]
 [-0.29515864]]

------

Get weights of output layer3 to hidden layer2 : [[0.29980885 0.69984848 0.49983675

# Part 2

##  Experiment with different weights, inputs, and targets.

#### 1. Change input values

In [71]:
# Generate input values for input layer1
input_values = [[1.0, 2.3, 4.4]]

# Generate the weights from input layer1 to hidden layer2
# weights_input_hidden = [[0.9,0.3,0.4],[0.2,0.8,0.2],[0.1,0.5,0.6]]

# Generate the weights from hidden layer2 to output layer3
# weights_hidden_output = [[0.3, 0.7, 0.5],[0.6, 0.5, 0.2],[0.8, 0.1, 0.9]]

# Generate the target values
# target = [[0.6,0.8,0.5]]

# Create an instance of neural network
n = neuralNetworkFirstStudy(input_values,weights_input_hidden,weights_hidden_output,target)


****** Forward Pass ******

Input values for input layer 1 :  [[1. ]
 [2.3]
 [4.4]]

------

Weights for input layer 1 to hidden layer 2 :  [[0.9 0.3 0.4]
 [0.2 0.8 0.2]
 [0.1 0.5 0.6]]

------

Weights for hidden layer 2 to output layer 3 :  [[0.3 0.7 0.5]
 [0.6 0.5 0.2]
 [0.8 0.1 0.9]]

------

Target values :  [[0.6]
 [0.8]
 [0.5]]

------

Input values for hidden layer2 before sigmoid function:  [[3.35]
 [2.92]
 [3.89]]

------

Input values for output layer 3 :  [[0.96610484]
 [0.9488263 ]
 [0.97996429]]

------

Input values for output layer3 before sigmoid function :  [[1.44399201]
 [1.25006891]
 [1.74973436]]

------

Output values for output layer3 after sigmoid function :  [[0.80907208]
 [0.77731179]
 [0.85191929]]

------


****** Backward Pass ******

Output errors :  [[-0.20907208]
 [ 0.02268821]
 [-0.35191929]]

------

Hidden error :  [[-0.33064413]
 [-0.17019828]
 [-0.41672576]]

------

Get weights of output layer3 to hidden layer2 : [[0.29968798 0.69969356 0.49968351

#### 2. Change target values

In [72]:
# Generate input values for input layer1
input_values = [[0.9, 0.1, 0.8]]

# Generate the weights from input layer1 to hidden layer2
# weights_input_hidden = [[0.9,0.3,0.4],[0.2,0.8,0.2],[0.1,0.5,0.6]]

# Generate the weights from hidden layer2 to output layer3
# weights_hidden_output = [[0.3, 0.7, 0.5],[0.6, 0.5, 0.2],[0.8, 0.1, 0.9]]

# Generate the target values
target = [[1.1,2.2,3.3]]

# Create an instance of neural network
n = neuralNetworkFirstStudy(input_values,weights_input_hidden,weights_hidden_output,target)


****** Forward Pass ******

Input values for input layer 1 :  [[0.9]
 [0.1]
 [0.8]]

------

Weights for input layer 1 to hidden layer 2 :  [[0.9 0.3 0.4]
 [0.2 0.8 0.2]
 [0.1 0.5 0.6]]

------

Weights for hidden layer 2 to output layer 3 :  [[0.3 0.7 0.5]
 [0.6 0.5 0.2]
 [0.8 0.1 0.9]]

------

Target values :  [[1.1]
 [2.2]
 [3.3]]

------

Input values for hidden layer2 before sigmoid function:  [[1.16]
 [0.42]
 [0.62]]

------

Input values for output layer 3 :  [[0.76133271]
 [0.60348325]
 [0.65021855]]

------

Input values for output layer3 before sigmoid function :  [[0.97594736]
 [0.88858496]
 [1.25461119]]

------

Output values for output layer3 after sigmoid function :  [[0.72630335]
 [0.70859807]
 [0.77809706]]

------


****** Backward Pass ******

Output errors :  [[0.37369665]
 [1.49140193]
 [2.52190294]]

------

Hidden error :  [[3.02447251]
 [1.25947892]
 [2.75484136]]

------

Get weights of output layer3 to hidden layer2 : [[0.30056556 0.7004483  0.50048302]
 [0.

#### 3. Change weights values

In [73]:
# Generate input values for input layer1
# input_values = [[0.9, 0.1, 0.8]]

# Generate the weights from input layer1 to hidden layer2
weights_input_hidden = [[0.1,0.3,0.5],[0.3,0.5,0.2],[0.7,0.9,0.4]]

# Generate the weights from hidden layer2 to output layer3
weights_hidden_output = [[0.1, 0.5, 0.3],[0.8, 0.5, 0.2],[0.1, 0.1, 0.1]]

# Generate the target values
target = [[0.6,0.8,0.5]]

# Create an instance of neural network
n = neuralNetworkFirstStudy(input_values,weights_input_hidden,weights_hidden_output,target)


****** Forward Pass ******

Input values for input layer 1 :  [[0.9]
 [0.1]
 [0.8]]

------

Weights for input layer 1 to hidden layer 2 :  [[0.1 0.3 0.5]
 [0.3 0.5 0.2]
 [0.7 0.9 0.4]]

------

Weights for hidden layer 2 to output layer 3 :  [[0.1 0.5 0.3]
 [0.8 0.5 0.2]
 [0.1 0.1 0.1]]

------

Target values :  [[0.6]
 [0.8]
 [0.5]]

------

Input values for hidden layer2 before sigmoid function:  [[0.52]
 [0.48]
 [1.04]]

------

Input values for output layer 3 :  [[0.62714777]
 [0.61774787]
 [0.73885001]]

------

Input values for output layer3 before sigmoid function :  [[0.59324372]
 [0.95836215]
 [0.19837456]]

------

Output values for output layer3 after sigmoid function :  [[0.64410906]
 [0.72279376]
 [0.54943164]]

------


****** Backward Pass ******

Output errors :  [[-0.04410906]
 [ 0.07720624]
 [-0.04943164]]

------

Hidden error :  [[ 0.05241092]
 [ 0.01160543]
 [-0.00273463]]

------

Get weights of output layer3 to hidden layer2 : [[0.09993659 0.49993754 0.29992529

## Summary

### numpy API:

- random.rand(shape) ：create randomly initialized matrix
- asarray(list) : covert list to numpy array / matrix
- T attrbute : computes the transpose of matrix
- dot(m1, m2) : compute dot product / matrix multiplication for matrixes m1 and m2

### scipy.special API:

- sigmoid_function = lambda x : scipy.special.expit(x) : call the sigmoid function

### Others:

- Konw how to do the **Forward Propagation** and **Backward Propagation**.